# teczt_elab

FROM ubuntu:18.04

# 切换目录
WORKDIR /
COPY docker docker

# 设置时区
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

# 设置DNS
RUN echo 'nameserver 223.6.6.6' > /etc/resolv.conf

# 更换源和更新系统
COPY docker/sources.list /etc/apt/sources.list
RUN apt-get -y update && apt-get upgrade -y

# 安装配置nginx
RUN apt-get install -y nginx

# 安装配置Supervisor
RUN apt-get install -y supervisor

# 安装Redis
Run apt-get install -y redis-server

# CURL
Run apt-get install -y curl
# Vim
Run apt-get install -y vim

RUN apt-get -y update && apt-get upgrade -y

# 安装PHP7.2
RUN apt-get install -y php-pear php7.2 php7.2-fpm
RUN apt-get install -y php7.2-tokenizer php7.2-mysql php7.2-curl php7.2-gd php7.2-memcached php7.2-redis php7.2-opcache php7.2-json php7.2-xml php7.2-mongodb php7.2-readline php7.2-zip php7.2-soap php7.2-mbstring php7.2-bcmath

# PHP-composer
RUN apt-get install -y composer && composer config -g repo.packagist composer https://mirrors.aliyun.com/composer/

# 安装NPM
Run apt-get install -y nodejs
Run apt-get install -y npm
Run npm config set registry https://registry.npm.taobao.org
Run npm install -g apidoc
Run npm install -g yarn
Run yarn global add cnpm

# 安装 Crontab
Run apt-get install -y cron

# 安装 screen
Run apt-get install -y screen

# 安装 SSH
Run apt-get install -y openssh-server openssh-client

# 切换目录
WORKDIR /var/www

# 修改权限和切换用户
RUN chown -R www-data:www-data /var/www/
RUN chmod +x /docker/entrypoint.sh

CMD ["/docker/entrypoint.sh"]
