version: "3"
services:
  dl_nginx_php:
    container_name: dl_nginx_php
    image: registry.cn-hangzhou.aliyuncs.com/gupo-base-image/laravel-runtime:ubuntu
    restart: always
    volumes:
      - D:/www:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/log:/usr/share/nginx/logs/
      - ./php/fpm:/etc/php/7.4/fpm
      - ./php/cli:/etc/php/7.4/cli
    ports:
      - 6010:6010
      - 33000:33000
      - 32730:32730
      - 32731:32731
      - 32732:32732
      - 32733:32733
      - 32734:32734

  dl_mysql:
    container_name: dl_mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - 33306:3306

  dl_redis:
    container_name: dl_redis
    image: redis:5.0
    restart: always
    volumes:
      - ./redis/:/usr/local/etc/redis

  dl_mongo:
    container_name: dl_mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    # command: --serviceExecutor adaptive
    volumes:
      - ./mongo:/etc/mongo
    # config:
    #   - /etc/mongo/mongod.conf

  dl_mongo_express:
    container_name: dl_mongo_express
    image: mongo-express
    restart: always
    ports:
      - 38081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@dl_mongo:27017/












